# SERVER
server.port=${PORT:8020}

# DATABASE
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/watchstore?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# DISABLE SPRING SECURITY
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# GIM PAY
gimpay.base-url=${GIMPAY_BASE_URL:https://omni-uat.gimpay.org/Cube/PayLink.svc/api}
gimpay.merchant-id=${GIMPAY_MERCHANT_ID:15670306513}
gimpay.terminal-id=${GIMPAY_TERMINAL_ID:12586005}
gimpay.shared-key=${GIMPAY_SHARED_KEY:98ea042a41ba7d4b921e19b7da43b63a}
gimpay.currency=${GIMPAY_CURRENCY:952}
gimpay.pay-link-type=${GIMPAY_PAY_LINK_TYPE:1}

# APP BASE URL
app.base-url=${APP_BASE_URL:http://localhost:8020}