# Profil production Railway
# Ce fichier est actif quand SPRING_PROFILES_ACTIVE=prod

# DATABASE Railway
spring.datasource.url=jdbc:mysql://maglev.proxy.rlwy.net:39713/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=KIBTKMwRJRwRquzpGVXiFOxGJnFCVnTO
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# DISABLE SPRING SECURITY
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration

# GIM PAY
gimpay.base-url=https://omni-uat.gimpay.org/Cube/PayLink.svc/api
gimpay.merchant-id=15670306513
gimpay.terminal-id=12586005
gimpay.shared-key=98ea042a41ba7d4b921e19b7da43b63a
gimpay.currency=952
gimpay.pay-link-type=1

# APP URL
app.base-url=https://chronos-backend-production.up.railway.app